// ============================================================
// PORTFOLIO DATA — srihari-portfolio
// ============================================================

import type { Project, Skill, Hobby } from "@/types";

// ── PROJECTS ──────────────────────────────────────────────
export const projects: Project[] = [
  {
    id: "deepfake",
    num: "001",
    rank: "S",
    title: "Deepfake Detection + Perpetrator Tracking System",
    overview:
      "A two-phase AI forensic pipeline operating at the intersection of computer vision, signal processing, unsupervised clustering, and distributed systems engineering.",
    detail: `Phase 1 builds an offline forensic pipeline that analyzes any video file and outputs: a manipulation probability score, fake-region heatmaps via Grad-CAM++, face identity clusters via ArcFace + HDBSCAN, and a suspected perpetrator network graph via NetworkX + Neo4j.\n\nPhase 2 scales this into a real-time social media monitoring system. Apache Kafka handles event streaming, Redis caches hot identities, Kubernetes orchestrates the detection pods, and FastAPI exposes the forensic endpoints.\n\nWhy it's S-rank: It combines 5 distinct engineering disciplines into a single coherent, production-grade pipeline. Few student projects operate at this architectural depth.`,
    tech: ["PyTorch 2.2", "EfficientNet-B2", "ArcFace", "MTCNN", "Grad-CAM++", "HDBSCAN", "NetworkX", "Neo4j", "FastAPI", "Docker", "Apache Kafka", "Redis", "Kubernetes"],
    github: "https://github.com/haricodes2970",
    githubLabel: "Private — View GitHub Profile",
  },
  {
    id: "vtu",
    num: "002",
    rank: "S",
    title: "THE-VTU-BOT — AI Chatbot for VTU Students",
    overview:
      "An AI-powered RAG chatbot that auto-scrapes official VTU circulars and PDFs, indexes them into a vector database, and answers student questions in natural language — from PhD regulations to exam schedules, in seconds.",
    detail: `The system runs a scheduled scraper (APScheduler) that hits the VTU website, extracts text from PDFs via pdfplumber + Tesseract OCR, and indexes chunks into Pinecone using fastembed ONNX embeddings.\n\nWhen a student asks a question, LangChain routes it through semantic retrieval from Pinecone into Groq's Llama 3.1, which generates a structured answer sourced directly from official documents. PostgreSQL + Redis handle session state and caching.\n\n**Why it's S-rank:** Scraping + OCR pipeline, embedding + vector search, LLM integration, scheduled background jobs, and full-stack Docker deployment — all working together. Hit 10+ non-trivial bugs during build (Python version conflicts, decommissioned LLM models, OOM on deployment, CORS, config caching). Built and fully deployed in one session.`,
    tech: ["FastAPI", "PostgreSQL", "Redis", "Pinecone", "Groq Llama 3.1", "fastembed (ONNX)", "LangChain", "spaCy", "BeautifulSoup", "pdfplumber", "Tesseract OCR", "APScheduler", "React", "TypeScript", "Tailwind CSS", "Docker"],
    github: "https://github.com/haricodes2970/THE-VTU-CHATBOT-",
    live: "https://the-vtu-chatbot.vercel.app",
  },
  {
    id: "bookyourevent",
    num: "003",
    rank: "A",
    title: "BookYourEvent",
    overview:
      "A full-stack multi-role venue booking platform handling the complete lifecycle from discovery to payment to in-app communication.",
    detail: `Three roles define the architecture: Bookers browse and filter venues, place instant bookings or competitive bids, pay via Razorpay, and message venue owners in-app. Venue Owners list spaces and manage media via Cloudinary. Admins approve venues and monitor platform-wide stats.\n\nAuth is handled via OTP-verified email (Nodemailer) and Google OAuth. The booking lifecycle — pending → confirmed → completed → reviewed — is automated with server-side state management.`,
    tech: ["React", "Vite", "Axios", "Node.js", "Express", "MongoDB", "Mongoose", "Razorpay", "Cloudinary", "Nodemailer", "Google OAuth"],
    github: "https://github.com/haricodes2970/BookYourEvent.git",
    live: "https://bookyourevnt.netlify.app/",
  },
  {
    id: "picy",
    num: "004",
    rank: "A",
    title: "Picy — Instant Image & Text Sharing",
    overview:
      "Zero-auth content sharing via custom URL. No login, no signup — just navigate, drop content, and share the link.",
    detail: `Navigate to picy.store/yourslug, drop an image or text, and the content is live immediately. Images upload to Cloudinary with a 24-hour auto-delete TTL. Text is stored in MongoDB Atlas with a 7-day TTL index.\n\nShipped solo in 3–4 hours, integrating 4 external services. Includes an admin dashboard, AdSense monetization, full PWA support, and SEO configuration. That's production-level thinking, not just a weekend hack.`,
    tech: ["React", "Vite", "Node.js", "Express", "MongoDB Atlas", "Cloudinary", "Netlify", "Render"],
    github: "https://github.com/haricodes2970/PiCy-PictureCopy",
    live: "https://picy.netlify.app",
  },
  {
    id: "toki",
    num: "005",
    rank: "A",
    title: "Toki — AI Token Usage Tracker",
    overview:
      "A privacy-first Chrome extension giving real-time visibility into your AI spending — before you hit limits or waste tokens.",
    detail: `Toki injects a content script into ChatGPT, Claude, Gemini, and Grok. It tokenizes prompts client-side using js-tiktoken (WASM) — the same tokenizer OpenAI uses — and accumulates usage into chrome.storage.local. Zero data leaves the browser.\n\nA battery-style overlay shows current usage. A pre-send warning fires when a prompt would push daily tokens over configurable limits. The prompt optimizer analyzes patterns in your prompts and suggests trimmed versions.`,
    tech: ["TypeScript", "React", "Tailwind CSS", "Vite", "Manifest V3", "vite-plugin-web-extension", "Recharts", "js-tiktoken (WASM)", "chrome.storage API"],
    github: "https://github.com/haricodes2970/Toki",
    note: "Chrome extension — not deployable as a web app.",
  },
  {
    id: "overlap",
    num: "006",
    rank: "A",
    title: "OverlapOptimizer",
    overview:
      "Detects semantic overlap across educational video courses and generates a deduplicated, optimized playlist — saving learners hours.",
    detail: `Four pipeline stages: (1) Transcription via OpenAI Whisper. (2) BERTopic segments transcripts into topical chunks. (3) Sentence-transformer embeddings indexed in FAISS detect cross-course overlap. (4) A merged learning path with precise skip timestamps is generated.\n\nThe Next.js frontend renders an interactive timeline UI where learners see which segments overlap, preview merged playlists, and export to YouTube or local m3u8.`,
    tech: ["Next.js", "Tailwind CSS", "FastAPI", "OpenAI Whisper", "Sentence-Transformers", "BERTopic", "FAISS", "PostgreSQL", "S3", "Docker"],
    wip: true,
    note: "🚧 In active development. GitHub link coming soon.",
  },
  {
    id: "timetrack",
    num: "007",
    rank: "B",
    title: "AI TimeTrack",
    overview:
      "A cross-platform active-time tracker — logs real engagement time across AI browser tools and AI coding assistants combined.",
    detail: `Two components: a Chrome Extension monitors tab focus and idle state across ChatGPT, Claude, Grok, and Gemini. A VS Code Extension hooks into editor activity events for Cursor, Copilot, and similar tools.\n\nActive detection uses idle timeouts, cross-tab deduplication, and IndexedDB crash recovery snapshots. A unified React dashboard shows per-AI breakdowns, 7/30-day trends, and usage streaks. 100% local-first, no backend.`,
    tech: ["TypeScript", "Manifest V3", "VS Code Extension API", "Vite", "React", "Tailwind CSS", "Recharts", "IndexedDB"],
    wip: true,
    note: "🚧 Work in progress. GitHub link coming when stable.",
  },
];

// ── SKILLS ────────────────────────────────────────────────
export const skills: Skill[] = [
  {
    styleName: "Santoryu — AI Mastery",
    name:      "Python",
    category:  "ai",
    level:     92,
    why:       "Python is my primary language. 92% because I write production-grade pipelines, not just scripts — but I'm not a CPython internals expert, and that's the honest ceiling.",
    tools:     ["NumPy", "Pandas", "scikit-learn", "FastAPI", "BeautifulSoup", "spaCy", "asyncio", "Poetry"],
    usedIn:    ["Deepfake Detection System", "VTU Smart Scheduler", "OverlapOptimizer"],
  },
  {
    styleName: "Haki — Deep Learning",
    name:      "PyTorch",
    category:  "ai",
    level:     78,
    why:       "I've trained custom CNNs, used EfficientNet with ArcFace embeddings, and implemented Grad-CAM++ visualizations. 78% because I haven't gone deep into custom CUDA kernels or advanced distributed training yet.",
    tools:     ["EfficientNet-B2", "ArcFace", "MTCNN", "Grad-CAM++", "torchvision", "torchaudio", "ONNX export"],
    usedIn:    ["Deepfake Detection System"],
  },
  {
    styleName: "Ittoryu — Agent Logic",
    name:      "LangChain",
    category:  "ai",
    level:     82,
    why:       "Built a full RAG pipeline with LangChain — custom retrievers, memory chains, Groq LLM routing. 82% because multi-agent orchestration with tools is still an area I'm deepening.",
    tools:     ["LangChain", "Groq Llama 3", "RAG pipelines", "Pinecone retriever", "PromptTemplate", "ConversationalChain"],
    usedIn:    ["VTU Smart Scheduler"],
  },
  {
    styleName: "Nitoryu — Semantic Search",
    name:      "Pinecone / FAISS",
    category:  "ai",
    level:     75,
    why:       "Implemented vector indexing, semantic retrieval with cosine similarity, and hybrid search. 75% because I've used it in projects but haven't tuned ANN index parameters at massive scale.",
    tools:     ["Pinecone", "FAISS", "Sentence-Transformers", "HuggingFace Embeddings", "HNSW index"],
    usedIn:    ["VTU Smart Scheduler", "OverlapOptimizer"],
  },
  {
    styleName: "Rokudo Dake — Prompt Craft",
    name:      "Prompt Engineering",
    category:  "ai",
    level:     90,
    why:       "Chain-of-thought, few-shot, system prompt design, token optimization — I've shipped prompt systems that reduced token usage by 40%+ in Toki. 90% because there's always a more creative approach.",
    tools:     ["Chain-of-Thought", "Few-shot prompting", "System prompt design", "OpenAI API", "Anthropic API", "Groq"],
    usedIn:    ["Toki", "VTU Smart Scheduler"],
  },
  {
    styleName: "Vision Strike — CV",
    name:      "Computer Vision",
    category:  "ai",
    level:     72,
    why:       "Used Grad-CAM++ for explainability and MTCNN for face detection in a real forensic pipeline. 72% because I'm still growing in real-time CV and multi-object tracking depth.",
    tools:     ["OpenCV", "MTCNN", "Grad-CAM++", "ArcFace", "HDBSCAN", "EfficientNet"],
    usedIn:    ["Deepfake Detection System"],
  },
  {
    styleName: "Santoryu — UI Mastery",
    name:      "React / Next.js",
    category:  "frontend",
    level:     86,
    why:       "Built full-stack apps with App Router, SSR, client/server components, and complex state. 86% because I'm still sharpening advanced patterns like streaming RSC and fine-grained Suspense.",
    tools:     ["React 18", "Next.js 15 App Router", "Framer Motion", "GSAP", "Zustand", "React Query", "Radix UI"],
    usedIn:    ["This Portfolio", "VTU Smart Scheduler", "BookYourEvent", "OverlapOptimizer"],
  },
  {
    styleName: "Speed Slash — Styling",
    name:      "Tailwind CSS",
    category:  "frontend",
    level:     90,
    why:       "My default styling layer. I build pixel-precise, responsive UIs fast with Tailwind. 90% because I haven't deeply explored JIT plugin authoring or complex token-based design systems.",
    tools:     ["Tailwind CSS v3", "PostCSS", "clsx", "tailwind-merge", "Custom plugins", "CSS variables"],
    usedIn:    ["This Portfolio", "VTU Smart Scheduler", "Toki", "BookYourEvent"],
  },
  {
    styleName: "Chrome Blade — Extensions",
    name:      "TypeScript",
    category:  "frontend",
    level:     78,
    why:       "I write typed React, typed APIs, and typed Chrome extensions. 78% because I lean on type inference heavily and haven't built complex generic utility types or type-level computation.",
    tools:     ["TypeScript 5", "Manifest V3", "Vite", "ESLint", "Generic types", "Discriminated unions"],
    usedIn:    ["Toki", "AI TimeTrack", "This Portfolio"],
  },
  {
    styleName: "Haki — System Control",
    name:      "Node.js / Express",
    category:  "backend",
    level:     84,
    why:       "Shipped multi-role REST APIs, WebSocket chats, and OTP auth flows. 84% because I haven't gone deep into Node cluster mode or worker threads for CPU-bound workloads.",
    tools:     ["Express.js", "Mongoose", "JWT", "Nodemailer", "Google OAuth", "Socket.IO", "multer"],
    usedIn:    ["BookYourEvent", "Picy"],
  },
  {
    styleName: "Stone Cutting — API Design",
    name:      "FastAPI",
    category:  "backend",
    level:     80,
    why:       "Built async ML inference APIs, Kafka producers, and websocket endpoints. 80% because advanced dependency injection patterns and background task queuing are still areas I'm formalizing.",
    tools:     ["FastAPI", "Pydantic v2", "asyncio", "Uvicorn", "APScheduler", "Kafka producers"],
    usedIn:    ["Deepfake Detection System", "VTU Smart Scheduler", "OverlapOptimizer"],
  },
  {
    styleName: "Demon Slash — Data",
    name:      "MongoDB / PostgreSQL",
    category:  "backend",
    level:     82,
    why:       "Designed schemas, TTL indexes, aggregation pipelines (MongoDB) and normalized relational schemas with full-text search (PostgreSQL). 82% because query optimization at massive scale is still a growth area.",
    tools:     ["MongoDB Atlas", "Mongoose", "PostgreSQL", "Prisma", "Redis", "Neo4j", "TTL indexes"],
    usedIn:    ["BookYourEvent", "Picy", "VTU Smart Scheduler", "Deepfake Detection System"],
  },
  {
    styleName: "Shadow Step — DevOps",
    name:      "Docker / Kubernetes",
    category:  "tools",
    level:     68,
    why:       "Containerized multiple services and deployed Kubernetes pods for the Deepfake pipeline. 68% because I can do it in production but Helm charts, advanced networking, and K8s operators are still frontier territory.",
    tools:     ["Docker", "Docker Compose", "Kubernetes", "Apache Kafka", "Redis", "Nginx"],
    usedIn:    ["Deepfake Detection System", "VTU Smart Scheduler"],
  },
  {
    styleName: "Spirit Wave — Integration",
    name:      "Cloudinary / Razorpay",
    category:  "tools",
    level:     85,
    why:       "Deep API integrations — media upload/transform pipelines (Cloudinary) and full payment lifecycle with webhooks (Razorpay). 85% because I've shipped them in production but haven't explored every advanced API feature.",
    tools:     ["Cloudinary SDK", "Razorpay API", "Webhooks", "Media transformation", "Upload presets"],
    usedIn:    ["BookYourEvent", "Picy"],
  },
  {
    styleName: "Swordsmith — Version Control",
    name:      "Git / GitHub",
    category:  "tools",
    level:     88,
    why:       "Daily driver. Branch strategy, PR reviews, CI/CD with GitHub Actions, rebase workflows. 88% because I haven't led large OSS projects with complex multi-maintainer merge strategies.",
    tools:     ["Git", "GitHub", "GitHub Actions", "Branch strategies", "Conventional Commits", "Vercel CI"],
    usedIn:    ["Every project"],
  },
];

// ── HOBBIES ───────────────────────────────────────────────
export const hobbies: Hobby[] = [
  { icon: "🎵", name: "Music",           desc: "Fuel for deep work" },
  { icon: "⚡", name: "Vibe Coding",     desc: "Shipping in flow state" },
  { icon: "⚔",  name: "Anime",           desc: "Otaku at heart" },
  { icon: "🎬", name: "Movies",          desc: "Stories that inspire" },
  { icon: "🔍", name: "New Tech",        desc: "Always first to explore" },
  { icon: "📜", name: "Ancient History", desc: "Civilizations that shaped us" },
  { icon: "🪔", name: "Indian Culture",  desc: "Ancient stories & wisdom" },
];
